from typing import Any, List, Tuple

from skopt.utils import Categorical, Dimension, Integer, Real

SPACE: List[Tuple[Dimension, Any]] = [
    (Categorical(["postgres", "postgres_verbose", "sql_standard", "iso_8601"], name="IntervalStyle"), "postgres"),
    (Categorical(["on", "off"], name="array_nulls"), "on"),
    (Integer(0, 256, name="backend_flush_after"), 0),
    (Categorical(["safe_encoding", "on", "off"], name="backslash_quote"), "safe_encoding"),
    (Categorical(["escape", "hex"], name="bytea_output"), "hex"),
    (Categorical(["on", "off"], name="check_function_bodies"), "on"),
    (Integer(0, 2147483647, name="client_connection_check_interval"), 0),
    (Categorical(["debug5", "debug4", "debug3", "debug2", "debug1", "log", "notice", "warning", "error"], name="client_min_messages"), "notice"),
    (Integer(0, 1000, name="commit_siblings"), 5),
    (Categorical(["partition", "on", "off"], name="constraint_exclusion"), "partition"),
    (Real(0.0, 1.79769e+308, name="cpu_index_tuple_cost"), 0.005),
    (Real(0.0, 1.79769e+308, name="cpu_operator_cost"), 0.0025),
    (Real(0.0, 1.79769e+308, name="cpu_tuple_cost"), 0.01),
    (Real(0.0, 1.0, name="cursor_tuple_fraction"), 0.1),
    (Categorical(["on", "off"], name="debug_pretty_print"), "on"),
    (Categorical(["on", "off"], name="debug_print_parse"), "off"),
    (Categorical(["on", "off"], name="debug_print_plan"), "off"),
    (Categorical(["on", "off"], name="debug_print_rewritten"), "off"),
    (Integer(1, 10000, name="default_statistics_target"), 100),
    (Categorical(["pglz"], name="default_toast_compression"), "pglz"),
    (Categorical(["on", "off"], name="default_transaction_deferrable"), "off"),
    (Categorical(["on", "off"], name="default_transaction_read_only"), "off"),
    (Integer(1, 2147483647, name="effective_cache_size"), 524288),
    (Integer(0, 1000, name="effective_io_concurrency"), 1),
    (Categorical(["on", "off"], name="enable_async_append"), "on"),
    (Categorical(["on", "off"], name="enable_bitmapscan"), "on"),
    (Categorical(["on", "off"], name="enable_gathermerge"), "on"),
    (Categorical(["on", "off"], name="enable_hashagg"), "on"),
    (Categorical(["on", "off"], name="enable_hashjoin"), "on"),
    (Categorical(["on", "off"], name="enable_incremental_sort"), "on"),
    (Categorical(["on", "off"], name="enable_indexonlyscan"), "on"),
    (Categorical(["on", "off"], name="enable_indexscan"), "on"),
    (Categorical(["on", "off"], name="enable_material"), "on"),
    (Categorical(["on", "off"], name="enable_memoize"), "on"),
    (Categorical(["on", "off"], name="enable_mergejoin"), "on"),
    (Categorical(["on", "off"], name="enable_nestloop"), "on"),
    (Categorical(["on", "off"], name="enable_parallel_append"), "on"),
    (Categorical(["on", "off"], name="enable_parallel_hash"), "on"),
    (Categorical(["on", "off"], name="enable_partition_pruning"), "on"),
    (Categorical(["on", "off"], name="enable_partitionwise_aggregate"), "off"),
    (Categorical(["on", "off"], name="enable_partitionwise_join"), "off"),
    (Categorical(["on", "off"], name="enable_seqscan"), "on"),
    (Categorical(["on", "off"], name="enable_seqscan_prefetch"), "off"),
    (Categorical(["on", "off"], name="enable_sort"), "on"),
    (Categorical(["on", "off"], name="enable_tidscan"), "on"),
    (Categorical(["on", "off"], name="escape_string_warning"), "on"),
    (Categorical(["on", "off"], name="exit_on_error"), "off"),
    (Integer(-15, 3, name="extra_float_digits"), 1),
    (Categorical(["off", "on", "regress"], name="force_parallel_mode"), "off"),
    (Integer(1, 2147483647, name="from_collapse_limit"), 8),
    (Categorical(["on", "off"], name="geqo"), "on"),
    (Integer(1, 10, name="geqo_effort"), 5),
    (Integer(0, 2147483647, name="geqo_generations"), 0),
    (Integer(0, 2147483647, name="geqo_pool_size"), 0),
    (Real(0.0, 1.0, name="geqo_seed"), 0.0),
    (Real(1.5, 2.0, name="geqo_selection_bias"), 2.0),
    (Integer(2, 2147483647, name="geqo_threshold"), 12),
    (Integer(0, 2147483647, name="gin_fuzzy_search_limit"), 0),
    (Integer(64, 2147483647, name="gin_pending_list_limit"), 4096),
    (Real(1.0, 1000.0, name="hash_mem_multiplier"), 1.0),
    (Integer(0, 2147483647, name="idle_in_transaction_session_timeout"), 0),
    (Integer(0, 2147483647, name="idle_session_timeout"), 0),
    # (Categorical(["on", "off"], name="ignore_system_indexes"), "off"), # Should be set using connection string
    (Categorical(["on", "off"], name="jit"), "on"),
    (Real(-1.0, 1.79769e+308, name="jit_above_cost"), 100000.0),
    (Categorical(["on", "off"], name="jit_expressions"), "on"),
    (Real(-1.0, 1.79769e+308, name="jit_inline_above_cost"), 500000.0),
    (Real(-1.0, 1.79769e+308, name="jit_optimize_above_cost"), 500000.0),
    (Categorical(["on", "off"], name="jit_tuple_deforming"), "on"),
    (Integer(1, 2147483647, name="join_collapse_limit"), 8),
    (Integer(0, 2147483647, name="lock_timeout"), 0),
    (Integer(-1, 2147483647, name="log_autovacuum_min_duration"), -1),
    (Categorical(["on", "off"], name="log_checkpoints"), "off"),
    (Categorical(["on", "off"], name="log_connections"), "off"),
    (Categorical(["on", "off"], name="log_disconnections"), "off"),
    (Categorical(["on", "off"], name="log_duration"), "off"),
    (Categorical(["terse", "default", "verbose"], name="log_error_verbosity"), "default"),
    (Categorical(["on", "off"], name="log_executor_stats"), "off"),
    (Categorical(["on", "off"], name="log_lock_waits"), "off"),
    (Integer(-1, 2147483647, name="log_min_duration_sample"), -1),
    (Integer(-1, 2147483647, name="log_min_duration_statement"), -1),
    (Categorical(["debug5", "debug4", "debug3", "debug2", "debug1", "info", "notice", "warning", "error", "log", "fatal", "panic"], name="log_min_error_statement"), "error"),
    (Categorical(["debug5", "debug4", "debug3", "debug2", "debug1", "info", "notice", "warning", "error", "log", "fatal", "panic"], name="log_min_messages"), "warning"),
    (Integer(-1, 1073741823, name="log_parameter_max_length_on_error"), 0),
    (Categorical(["on", "off"], name="log_planner_stats"), "off"),
    (Categorical(["on", "off"], name="log_recovery_conflict_waits"), "off"),
    (Categorical(["none", "ddl", "mod", "all"], name="log_statement"), "none"),
    (Categorical(["on", "off"], name="log_statement_stats"), "off"),
    (Real(0.0, 1.0, name="log_transaction_sample_rate"), 0.0),
    (Integer(64, 2147483647, name="logical_decoding_work_mem"), 65536),
    (Integer(0, 1000, name="maintenance_io_concurrency"), 10),
    (Integer(1024, 2147483647, name="maintenance_work_mem"), 65536),
    (Integer(0, 1024, name="max_parallel_maintenance_workers"), 2),
    (Integer(0, 1024, name="max_parallel_workers"), 8),
    (Integer(0, 1024, name="max_parallel_workers_per_gather"), 2),
    (Integer(0, 715827882, name="min_parallel_index_scan_size"), 64),
    (Integer(0, 715827882, name="min_parallel_table_scan_size"), 1024),
    (Categorical(["on", "off"], name="parallel_leader_participation"), "on"),
    (Real(0.0, 1.79769e+308, name="parallel_setup_cost"), 1000.0),
    (Real(0.0, 1.79769e+308, name="parallel_tuple_cost"), 0.1),
    (Categorical(["auto", "force_generic_plan", "force_custom_plan"], name="plan_cache_mode"), "auto"),
    # (Integer(0, 2147, name="post_auth_delay"), 0), # Should be set using connection string
    (Categorical(["on", "off"], name="quote_all_identifiers"), "off"),
    (Real(0.0, 1.79769e+308, name="random_page_cost"), 4.0),
    (Categorical(["on", "off"], name="row_security"), "on"),
    (Real(0.0, 1.79769e+308, name="seq_page_cost"), 1.0),
    (Integer(0, 1000, name="seqscan_prefetch_buffers"), 0),
    (Categorical(["on", "off"], name="standard_conforming_strings"), "on"),
    (Integer(0, 2147483647, name="statement_timeout"), 0),
    (Categorical(["on", "off"], name="synchronize_seqscans"), "on"),
    (Categorical(["local", "remote_write", "remote_apply", "on", "off"], name="synchronous_commit"), "on"),
    (Integer(0, 2147483647, name="tcp_keepalives_count"), 0),
    (Integer(0, 2147483647, name="tcp_keepalives_idle"), 0),
    (Integer(0, 2147483647, name="tcp_keepalives_interval"), 0),
    (Integer(0, 2147483647, name="tcp_user_timeout"), 0),
    (Integer(100, 1073741823, name="temp_buffers"), 1024),
    (Categorical(["on", "off"], name="trace_notify"), "off"),
    (Categorical(["on", "off"], name="trace_sort"), "off"),
    # (Categorical(["on", "off"], name="transaction_read_only"), "off"), # Invompatible with pgbench --initialize
    (Categorical(["on", "off"], name="transform_null_equals"), "off"),
    (Real(0.0, 100.0, name="vacuum_cost_delay"), 0.0),
    (Integer(1, 10000, name="vacuum_cost_limit"), 200),
    (Integer(0, 10000, name="vacuum_cost_page_dirty"), 20),
    (Integer(0, 10000, name="vacuum_cost_page_hit"), 1),
    (Integer(0, 10000, name="vacuum_cost_page_miss"), 2),
    (Integer(0, 2100000000, name="vacuum_failsafe_age"), 1600000000),
    (Integer(0, 1000000000, name="vacuum_freeze_min_age"), 50000000),
    (Integer(0, 2000000000, name="vacuum_freeze_table_age"), 150000000),
    (Integer(0, 2100000000, name="vacuum_multixact_failsafe_age"), 1600000000),
    (Integer(0, 1000000000, name="vacuum_multixact_freeze_min_age"), 5000000),
    (Integer(0, 2000000000, name="vacuum_multixact_freeze_table_age"), 150000000),
    (Integer(0, 2147483647, name="wal_sender_timeout"), 60000),
    (Integer(0, 2147483647, name="wal_skip_threshold"), 2048),
    (Integer(64, 2147483647, name="work_mem"), 4096),
    (Categorical(["base64", "hex"], name="xmlbinary"), "base64"),
    (Categorical(["content", "document"], name="xmloption"), "content"),
]

ALLOWED_SERVER_SETTINGS: List[str] = [
    "constraint_exclusion",
    "cpu_index_tuple_cost",
    "cpu_operator_cost",
    "cpu_tuple_cost",
    "cursor_tuple_fraction",
    "debug_pretty_print",
    "debug_print_parse",
    "debug_print_plan",
    "debug_print_rewritten",
    "enable_async_append",
    "enable_bitmapscan",
    "enable_gathermerge",
    "enable_hashagg",
    "enable_hashjoin",
    "enable_incremental_sort",
    "enable_indexonlyscan",
    "enable_indexscan",
    "enable_material",
    "enable_mergejoin",
    "enable_nestloop",
    "enable_parallel_append",
    "enable_parallel_hash",
    "enable_partition_pruning",
    "enable_partitionwise_aggregate",
    "enable_partitionwise_join",
    "enable_resultcache",
    "enable_seqscan",
    "enable_sort",
    "enable_tidscan",
    "escape_string_warning",
    "exit_on_error",
    "from_collapse_limit",
    "idle_in_transaction_session_timeout",
    "idle_session_timeout",
    "lock_timeout",
    "log_autovacuum_min_duration",
    "log_checkpoints",
    "log_connections",
    "log_disconnections",
    "log_duration",
    "log_error_verbosity",
    "log_executor_stats",
    "log_lock_waits",
    "log_min_duration_sample",
    "log_min_duration_statement",
    "log_min_error_statement",
    "log_min_messages",
    "log_planner_stats",
    "log_recovery_conflict_waits",
    "log_statement",
    "log_statement_stats",
    "log_transaction_sample_rate",
    "min_parallel_table_scan_size",
    "parallel_setup_cost",
    "parallel_tuple_cost",
    "plan_cache_mode",
    "random_page_cost",
    "seq_page_cost",
    "statement_timeout",
    "transaction_isolation",
]
